

// 整个APP的state
export const APP_SHOW_LOADING_REQUESTED = 'APP_SHOW_LOADING_REQUESTED'
export const APP_HIDE_LOADING_REQUESTED = 'APP_HIDE_LOADING_REQUESTED'
export const APP_SHOW_TOAST_REQUESTED = 'APP_SHOW_TOAST_REQUESTED'
export const APP_HIDE_TOAST_REQUESTED = 'APP_HIDE_TOAST_REQUESTED'

// 导航
export const Navigation_POPN = `Navigation/POPN`;
export const Navigation_RESETTO = `Navigation/RESETTO`;
export const Navigation_POPTOTOP = `Navigation/POPTOTOP`;
export const Navigation_POPTOINDEX = `Navigation/POPTOINDEX`;
export const Navigation_POPTOROUTE = `Navigation/POPTOROUTE`;
export const Navigation_RESETTOORDERINDEX = `Navigation_RESETTOORDERINDEX`;

export const APP_CHANGE_NET_INFO = 'APP_CHANGE_NET_INFO'
export const APP_ORIENTATION_INFO_CHANGED = 'APP_ORIENTATION_INFO_CHANGED'
export const APP_CHANGE_STATUS_BARSTYLE = 'APP_CHANGE_STATUS_BARSTYLE'
export const APP_CHANGE_STATUS_HIDE = 'APP_CHANGE_STATUS_HIDE'



//登录-注册模块
export const LOGIN_SET_LOGIN_CODE = `LOGIN_SET_LOGIN_CODE`;
export const LOGIN_GET_TOKEN = `LOGIN_GET_TOKEN`;
export const LOGIN_USERLOGIN = `LOGIN_USERLOGIN`;
export const LOGIN_REFRESH_TOKEN = `LOGIN_REFRESH_TOKEN`;
export const LOGIN_LOGOUT = `LOGIN_LOGOUT`;
export const LOGIN_GET_USER_INFO = `LOGIN_GET_USER_INFO`;
export const LOGIN_GET_DATA_DICT = `LOGIN_GET_DATA_DICT`;
export const LOGIN_GET_WARNING_SETTING_DICT = `LOGIN_GET_WARNING_SETTING_DICT`;
export const LOGIN_GET_REGION_DICT = `LOGIN_GET_REGION_DICT`;
export const LOGIN_SEND_VERIFY_CODE = `LOGIN_SEND_VERIFY_CODE`;
export const LOGIN_VERIFY_VERIFY_CODE = `LOGIN_VERIFY_VERIFY_CODE`;
export const LOGIN_CLEAR_VERIFY_CODE = `LOGIN_CLEAR_VERIFY_CODE`;
export const LOGIN_VERIFY_PHONE_AND_CODE = `LOGIN_VERIFY_PHONE_AND_CODE`;
export const LOGIN_SET_PASSWORD = `LOGIN_SET_PASSWORD`;
export const LOGIN_VERIFY_CHILD_INFO = `LOGIN_VERIFY_CHILD_INFO`;
export const APP_REGISTER = `APP_REGISTER`;
export const APP_REGISTER_FILL_INFO = `APP_REGISTER_FILL_INFO`;
export const APP_CLEAR_REGISTER_INFO = `APP_CLEAR_REGISTER_INFO`;
export const APP_VERIFY_PHONE_PASSWORD = `APP_VERIFY_PHONE_PASSWORD`;
export const APP_CHANGE_USER_PHONE = `APP_CHANGE_USER_PHONE`;
export const APP_GET_AGENT_INFO = `APP_GET_AGENT_INFO`;
export const APP_CLEAR_AGENT_INFO = `APP_CLEAR_AGENT_INFO`;
export const APP_SET_JPUSH_REGISTRATION_ID = `APP_SET_JPUSH_REGISTRATION_ID`;

//用户信息
export const HOME_UPDATE_IS_NIGHT = `HOME_UPDATE_IS_NIGHT`;
export const HOME_GET_GROW_INFO = `HOME_GET_GROW_INFO`;
export const HOME_COLLECT_ENERGY_BALL = `HOME_COLLECT_ENERGY_BALL`;
export const HOME_GET_SCHOOLMATE_GROW_INFO = `HOME_GET_SCHOOLMATE_GROW_INFO`;
export const HOME_CLEAR_SCHOOLMATE_GROW_INFO = `HOME_CLEAR_SCHOOLMATE_GROW_INFO`;
export const HOME_GET_TITLE_LIST = `HOME_GET_TITLE_LIST`;
export const HOME_GET_CLASS_LIST = `HOME_GET_CLASS_LIST`;
export const HOME_GET_CLASS_DETAIL = `HOME_GET_CLASS_DETAIL`;
export const HOME_CLEAR_CLASS_DETAIL = `HOME_CLEAR_CLASS_DETAIL`;
export const HOME_GET_ENERGY_BILL_LIST = `HOME_GET_ENERGY_BILL_LIST`;
export const HOME_CLEAR_ENERGY_BILL_LIST = `HOME_CLEAR_ENERGY_BILL_LIST`;
export const HOME_GET_ENERGY_BILL_DETAIL = `HOME_GET_ENERGY_BILL_DETAIL`;
export const HOME_CLEAR_ENERGY_BILL_DETAIL = `HOME_CLEAR_ENERGY_BILL_DETAIL`;

//用户信息
export const PROFILE_UPLOAD_USER_PORTRAIT = `PROFILE_UPLOAD_USER_PORTRAIT`;
export const PROFILE_GET_USER_INFO = `PROFILE_GET_USER_INFO`;
export const PROFILE_UPDATE_USER_INFO = `PROFILE_UPDATE_USER_INFO`;
export const PROFILE_ADD_CHILD = `PROFILE_ADD_CHILD`;
export const PROFILE_GET_CHILDREN_LIST = `PROFILE_GET_CHILDREN_LIST`;
export const PROFILE_SWITCH_CHILD = `PROFILE_SWITCH_CHILD`;
export const PROFILE_UPLOAD_CHILD_PORTRAIT = `PROFILE_UPLOAD_CHILD_PORTRAIT`;
export const PROFILE_TOGGLE_PUSH_STATE = `PROFILE_TOGGLE_PUSH_STATE`;
export const PROFILE_TOGGLE_PUSH_STATE_PRE_SET = `PROFILE_TOGGLE_PUSH_STATE_PRE_SET`;
export const PROFILE_TOGGLE_PUSH_STATE_RECOVER = `PROFILE_TOGGLE_PUSH_STATE_RECOVER`;
export const PROFILE_GET_CHILD_INFO = `PROFILE_GET_CHILD_INFO`;
export const PROFILE_CLEAR_CHILD_INFO = `PROFILE_CLEAR_CHILD_INFO`;
export const PROFILE_UPDATE_CHILD_INFO = `PROFILE_UPDATE_CHILD_INFO`;
export const PROFILE_GET_FAQ_LIST = `PROFILE_GET_FAQ_LIST`;
export const PROFILE_CLEAR_FAQ_LIST = `PROFILE_CLEAR_FAQ_LIST`;
export const PROFILE_GET_PERSON_INFO = `PROFILE_GET_PERSON_INFO`;
export const PROFILE_CLEAR_PERSON_INFO = `PROFILE_CLEAR_PERSON_INFO`;
export const PROFILE_GET_PERSON_BLOG_LIST = `PROFILE_GET_PERSON_BLOG_LIST`;
export const PROFILE_CLEAR_PERSON_BLOG_LIST = `PROFILE_CLEAR_PERSON_BLOG_LIST`;
export const PROFILE_GET_PERSON_SIGNATURE = `PROFILE_GET_PERSON_SIGNATURE`;
export const PROFILE_GET_PERSON_ALIAS_BY_NAME = `PROFILE_GET_PERSON_ALIAS_BY_NAME`;

//博客
export const BLOG_GET_PERSONAL_BLOGLIST = `BLOG_GET_PERSONAL_BLOGLIST`;
export const BLOG_CLEAR_PERSONAL_BLOGLIST = `BLOG_CLEAR_PERSONAL_BLOGLIST`;
export const BLOG_GET_PICKED_BLOGLIST = `BLOG_GET_PICKED_BLOGLIST`;
export const BLOG_CLEAR_PICKED_BLOGLIST = `BLOG_CLEAR_PICKED_BLOGLIST`;
export const BLOG_GET_HOME_BLOGLIST = `BLOG_GET_HOME_BLOGLIST`;
export const BLOG_CLEAR_HOME_BLOGLIST = `BLOG_CLEAR_HOME_BLOGLIST`;
export const BLOG_GET_FOLLOWING_BLOGLIST = `BLOG_GET_FOLLOWING_BLOGLIST`;
export const BLOG_CLEAR_FOLLOWING_BLOGLIST = `BLOG_CLEAR_FOLLOWING_BLOGLIST`;
export const BLOG_GET_DETAIL = `BLOG_GET_DETAIL`;
export const BLOG_CLEAR_DETAIL = `BLOG_CLEAR_DETAIL`;
export const BLOG_GET_BLOG_COMMENT_LIST = `BLOG_GET_BLOG_COMMENT_LIST`;
export const BLOG_CLEAR_BLOG_COMMENT_LIST = `BLOG_CLEAR_BLOG_COMMENT_LIST`;
export const BLOG_COMMENT_BLOG = `BLOG_COMMENT_BLOG`;
export const BLOG_SET_SELECTED_BLOG = `BLOG_SET_SELECTED_BLOG`;
export const BLOG_SET_BLOG_SCROLL_POSITION = `BLOG_SET_BLOG_SCROLL_POSITION`;


//新闻
export const NEWS_GET_LIST = `NEWS_GET_LIST`;
export const NEWS_CLEAR_LIST = `NEWS_CLEAR_LIST`;
export const NEWS_GET_HOT_WREEK_LIST = `NEWS_GET_HOT_WREEK_LIST`;
export const NEWS_CLEAR_HOT_WREEK_LIST = `NEWS_CLEAR_HOT_WREEK_LIST`;
export const NEWS_GET_RECOMMENDED_NEWS_LIST = `NEWS_GET_RECOMMENDED_NEWS_LIST`;
export const NEWS_CLEAR_RECOMMENDED_NEWS_LIST = `NEWS_CLEAR_RECOMMENDED_NEWS_LIST`;
export const NEWS_SET_SELECTED_DETAIL = `NEWS_SET_SELECTED_DETAIL`;
export const NEWS_GET_DETAIL = `NEWS_GET_DETAIL`;
export const NEWS_CLEAR_DETAIL = `NEWS_CLEAR_DETAIL`;
export const NEWS_COMMENT = `NEWS_COMMENT`;
export const NEWS_GET_COMMENT_LIST = `NEWS_GET_COMMENT_LIST`;
export const NEWS_CLEAR_COMMENT_LIST = `NEWS_CLEAR_COMMENT_LIST`;
export const NEWS_COMMENT_DELETE = `NEWS_COMMENT_DELETE`;
export const NEWS_COMMENT_MODIFY = `NEWS_COMMENT_MODIFY`;
export const NEWS_SET_NEWS_SCROLL_POSITION = `NEWS_SET_NEWS_SCROLL_POSITION`;

//闪存
export const STATUS_GET_LIST = `STATUS_GET_LIST`;
export const STATUS_CLEAR_LIST = `STATUS_CLEAR_LIST`;
export const STATUS_GET_DETAIL = `STATUS_GET_DETAIL`;
export const STATUS_CLEAR_DETAIL = `STATUS_CLEAR_DETAIL`;
export const STATUS_GET_COMMENT_LIST = `STATUS_GET_COMMENT_LIST`;
export const STATUS_CLEAR_COMMENT_LIST = `STATUS_CLEAR_COMMENT_LIST`;
export const STATUS_COMMENT_STATUS = `STATUS_COMMENT_STATUS`;
export const STATUS_DELETE_COMMENT = `STATUS_DELETE_COMMENT`;
export const STATUS_DELETE_STATUS = `STATUS_DELETE_STATUS`;
export const STATUS_ADD_STATUS = `STATUS_ADD_STATUS`;



//收藏
export const BOOKMARK_GET_LIST = `BOOKMARK_GET_LIST`;
export const BOOKMARK_CLEAR_LIST = `BOOKMARK_CLEAR_LIST`;
export const BOOKMARK_DELETE = `BOOKMARK_DELETE`;
export const BOOKMARK_DELETE_BYURL = `BOOKMARK_DELETE_BYURL`;
export const BOOKMARK_ADD = `BOOKMARK_ADD`;
export const BOOKMARK_MODIFY = `BOOKMARK_MODIFY`;
export const BOOKMARK_CHECK_IS = `BOOKMARK_CHECK_IS`;
export const BOOKMARK_SET_IS_FAV = `BOOKMARK_SET_IS_FAV`;
export const BOOKMARK_CLEAR_IS_FAV = `BOOKMARK_CLEAR_IS_FAV`;

//问题
export const QUESTION_GET_LIST = `QUESTION_GET_LIST`;
export const QUESTION_CLEAR_LIST = `QUESTION_CLEAR_LIST`;
export const QUESTION_CHECK_IS_ANSWERED = `QUESTION_CHECK_IS_ANSWERED`;
export const QUESTION_GET_DETAIL = `QUESTION_GET_DETAIL`;
export const QUESTION_CLEAR_DETAIL = `QUESTION_CLEAR_DETAIL`;
export const QUESTION_SET_SELECTED_QUESTION = `QUESTION_SET_SELECTED_QUESTION`;
export const QUESTION_GET_COMMENT_LIST = `QUESTION_GET_COMMENT_LIST`;
export const QUESTION_CLEAR_COMMENT_LIST = `QUESTION_CLEAR_COMMENT_LIST`;
export const QUESTION_GET_ANSWER_LIST = `QUESTION_GET_ANSWER_LIST`;
export const QUESTION_CLEAR_ANSWER_LIST = `QUESTION_CLEAR_ANSWER_LIST`;
export const QUESTION_ANSWER = `QUESTION_ANSWER`;
export const QUESTION_ADD_QUESTION = `QUESTION_ADD_QUESTION`;
export const QUESTION_DELETE_QUESTION = `QUESTION_DELETE_QUESTION`;
export const QUESTION_MODIFY_QUESTION = `QUESTION_MODIFY_QUESTION`;
export const QUESTION_DELETE_ANSWER = `QUESTION_DELETE_ANSWER`;
export const QUESTION_MODIFY_ANSWER = `QUESTION_MODIFY_ANSWER`;
export const QUESTION_SET_SELECTED_ANSWER = `QUESTION_SET_SELECTED_ANSWER`;
export const QUESTION_GET_ANSWER_COMMENT_LIST = `QUESTION_GET_ANSWER_COMMENT_LIST`;
export const QUESTION_CLEAR_ANSWER_COMMENT_LIST = `QUESTION_CLEAR_ANSWER_COMMENT_LIST`;
export const QUESTION_COMMENT_ANSWER = `QUESTION_COMMENT_ANSWER`;
export const QUESTION_DELETE_COMMENT_ANSWER = `QUESTION_DELETE_COMMENT_ANSWER`;
export const QUESTION_MODIFY_COMMENT_ANSWER = `QUESTION_MODIFY_COMMENT_ANSWER`;


//知识库
export const KNOWLEDGEBASE_GET_IST = `KNOWLEDGEBASE_GET_IST`;
export const KNOWLEDGEBASE_CLEAR_IST = `KNOWLEDGEBASE_CLEAR_IST`;
export const KNOWLEDGEBASE_GET_DETAIL = `KNOWLEDGEBASE_GET_DETAIL`;
export const KNOWLEDGEBASE_CLEAR_DETAIL = `KNOWLEDGEBASE_CLEAR_DETAIL`;

//首页
export const HOME_GET_LIST = `HOME_GET_LIST`;
export const HOME_CLEAR_LIST = `HOME_CLEAR_LIST`;
export const HOME_SEARCH_GET_LIST = `HOME_SEARCH_GET_LIST`;
export const HOME_SEARCH_CLEAR_LIST = `HOME_SEARCH_CLEAR_LIST`;
export const HOME_GET_DETAIL = `HOME_GET_DETAIL`;
export const HOME_CLEAR_DETAIL = `HOME_CLEAR_DETAIL`;
export const HOME_SET_DETAIL = `HOME_SET_DETAIL`;
export const HOME_REFRESH_DATA_TIME = `HOME_REFRESH_DATA_TIME`;

